@echo off
echo Starting MediManage AI Engine...
echo Ensure you have Python installed and requirements satisfied.
echo Installing requirements if needed...
pip install -r ai_engine/requirements.txt
echo Starting Server...
python ai_engine/server.py
pause
