-- PostgreSQL Schema for MediManage
-- 1. USERS
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'STAFF'
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username);
-- 2. MEDICINES
CREATE TABLE IF NOT EXISTS medicines (
    medicine_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    generic_name TEXT,
    company TEXT,
    price DOUBLE PRECISION NOT NULL,
    expiry_date DATE,
    active INTEGER DEFAULT 1
);
-- 3. STOCK
CREATE TABLE IF NOT EXISTS stock (
    stock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id INTEGER,
    quantity INTEGER NOT NULL,
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id)
);
-- 4. CUSTOMERS
CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address TEXT,
    nominee_name TEXT,
    nominee_relation TEXT,
    insurance_provider TEXT,
    insurance_policy_no TEXT,
    diseases TEXT,
    photo_id_path TEXT,
    current_balance DOUBLE PRECISION DEFAULT 0.0
);
-- 5. BILLS
CREATE TABLE IF NOT EXISTS bills (
    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER,
    user_id INTEGER,
    total_amount DOUBLE PRECISION,
    bill_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_mode TEXT DEFAULT 'CASH',
    ai_care_protocol TEXT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
-- 6. BILL ITEMS
CREATE TABLE IF NOT EXISTS bill_items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INTEGER,
    medicine_id INTEGER,
    quantity INTEGER,
    price DOUBLE PRECISION,
    total DOUBLE PRECISION,
    FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id)
);
-- 7. EXPENSES
CREATE TABLE IF NOT EXISTS expenses (
    expense_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    date DATE NOT NULL,
    description TEXT
);
-- 7A. INVENTORY ADJUSTMENTS (RETURNS / DAMAGES)
CREATE TABLE IF NOT EXISTS inventory_adjustments (
    adjustment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id INTEGER NOT NULL,
    adjustment_type TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    root_cause_tag TEXT,
    notes TEXT,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id INTEGER,
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(user_id),
    CHECK (adjustment_type IN ('RETURN', 'DAMAGED'))
);
-- 7B. WEEKLY ANOMALY ACTION TRACKER
CREATE TABLE IF NOT EXISTS anomaly_action_tracker (
    action_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_date TEXT NOT NULL,
    week_end_date TEXT NOT NULL,
    timezone_name TEXT NOT NULL,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    metric_value TEXT,
    threshold_rule TEXT,
    alert_message TEXT,
    owner_user_id INTEGER,
    due_date TEXT,
    closure_status TEXT NOT NULL DEFAULT 'OPEN',
    closed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    CHECK (
        closure_status IN ('OPEN', 'IN_PROGRESS', 'CLOSED')
    ),
    UNIQUE (week_start_date, timezone_name, alert_type)
);
-- 7C. ANALYTICS REPORT DISPATCH SCHEDULES
CREATE TABLE IF NOT EXISTS analytics_report_dispatch_schedules (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL,
    recipient TEXT NOT NULL,
    report_format TEXT NOT NULL,
    frequency TEXT NOT NULL,
    timezone_name TEXT NOT NULL,
    filter_start_date TEXT,
    filter_end_date TEXT,
    supplier_filter TEXT,
    category_filter TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    next_run_at TEXT NOT NULL,
    last_run_at TEXT,
    last_status TEXT,
    last_error TEXT,
    created_by_user_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_user_id) REFERENCES users(user_id),
    CHECK (channel IN ('EMAIL', 'WHATSAPP')),
    CHECK (report_format IN ('PDF', 'EXCEL', 'CSV')),
    CHECK (frequency IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    CHECK (active IN (0, 1))
);
-- ======================== PERFORMANCE INDEXES ========================
CREATE INDEX IF NOT EXISTS idx_medicines_name ON medicines(name);
CREATE INDEX IF NOT EXISTS idx_medicines_active_name ON medicines(active, name);
CREATE INDEX IF NOT EXISTS idx_medicines_company ON medicines(company);
CREATE INDEX IF NOT EXISTS idx_medicines_expiry ON medicines(expiry_date);
CREATE INDEX IF NOT EXISTS idx_stock_medicine ON stock(medicine_id);
CREATE INDEX IF NOT EXISTS idx_bills_date ON bills(bill_date);
CREATE INDEX IF NOT EXISTS idx_bills_customer ON bills(customer_id);
CREATE INDEX IF NOT EXISTS idx_bill_items_bill ON bill_items(bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_items_medicine ON bill_items(medicine_id);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);
CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_medicine ON inventory_adjustments(medicine_id);
CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_type_date ON inventory_adjustments(adjustment_type, occurred_at);
CREATE INDEX IF NOT EXISTS idx_anomaly_action_tracker_week ON anomaly_action_tracker(week_start_date, timezone_name);
CREATE INDEX IF NOT EXISTS idx_anomaly_action_tracker_status_due ON anomaly_action_tracker(closure_status, due_date);
CREATE INDEX IF NOT EXISTS idx_report_dispatch_schedule_next_run ON analytics_report_dispatch_schedules(active, next_run_at);
CREATE INDEX IF NOT EXISTS idx_report_dispatch_schedule_channel ON analytics_report_dispatch_schedules(channel, recipient);
-- ======================== MIGRATIONS ========================
ALTER TABLE medicines
ADD COLUMN generic_name TEXT;
ALTER TABLE customers
ADD COLUMN current_balance DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE bills
ADD COLUMN payment_mode TEXT DEFAULT 'CASH';
ALTER TABLE bills
ADD COLUMN ai_care_protocol TEXT;
ALTER TABLE medicines
ADD COLUMN active INTEGER DEFAULT 1;
CREATE INDEX IF NOT EXISTS idx_medicines_generic ON medicines(generic_name);
-- 8. PRESCRIPTIONS
CREATE TABLE IF NOT EXISTS prescriptions (
    prescription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER,
    customer_name TEXT NOT NULL,
    doctor_name TEXT,
    status TEXT DEFAULT 'PENDING',
    prescribed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    medicines_text TEXT,
    ai_validation TEXT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
CREATE INDEX IF NOT EXISTS idx_prescriptions_customer ON prescriptions(customer_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_status ON prescriptions(status);
CREATE INDEX IF NOT EXISTS idx_prescriptions_status_date ON prescriptions(status, prescribed_date DESC);
-- 8A. AI PROMPT REGISTRY
CREATE TABLE IF NOT EXISTS ai_prompt_registry (
    prompt_version_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_key TEXT NOT NULL,
    version_number INTEGER NOT NULL,
    template_text TEXT NOT NULL,
    change_type TEXT NOT NULL,
    change_note TEXT,
    rolled_back_from_version INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    changed_by_user_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(prompt_key, version_number),
    FOREIGN KEY (changed_by_user_id) REFERENCES users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_ai_prompt_registry_active ON ai_prompt_registry(prompt_key, is_active, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_ai_prompt_registry_history ON ai_prompt_registry(prompt_key, version_number DESC);
-- 9. SUBSCRIPTION PLANS
CREATE TABLE IF NOT EXISTS subscription_plans (
    plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code TEXT UNIQUE NOT NULL,
    plan_name TEXT NOT NULL,
    description TEXT,
    price DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    duration_days INTEGER NOT NULL,
    grace_days INTEGER NOT NULL DEFAULT 0,
    default_discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    max_discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    minimum_margin_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    auto_renew BOOLEAN NOT NULL DEFAULT FALSE,
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id INTEGER,
    updated_by_user_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(user_id),
    CHECK (
        status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'RETIRED')
    )
);
-- 10. SUBSCRIPTION PLAN CATEGORY RULES
CREATE TABLE IF NOT EXISTS subscription_plan_category_rules (
    rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INTEGER NOT NULL,
    category_name TEXT NOT NULL,
    include_rule BOOLEAN NOT NULL DEFAULT TRUE,
    discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    max_discount_amount DOUBLE PRECISION,
    min_margin_percent DOUBLE PRECISION,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(plan_id) ON DELETE CASCADE
);
-- 11. SUBSCRIPTION PLAN MEDICINE RULES
CREATE TABLE IF NOT EXISTS subscription_plan_medicine_rules (
    rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    include_rule BOOLEAN NOT NULL DEFAULT TRUE,
    discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    max_discount_amount DOUBLE PRECISION,
    min_margin_percent DOUBLE PRECISION,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(plan_id) ON DELETE CASCADE,
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id)
);
-- 12. CUSTOMER SUBSCRIPTIONS (ENROLLMENTS)
CREATE TABLE IF NOT EXISTS customer_subscriptions (
    enrollment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    grace_end_date TIMESTAMP,
    enrollment_channel TEXT,
    enrolled_by_user_id INTEGER,
    approved_by_user_id INTEGER,
    approval_reference TEXT,
    cancellation_reason TEXT,
    frozen_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(plan_id),
    FOREIGN KEY (enrolled_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (approved_by_user_id) REFERENCES users(user_id),
    CHECK (
        status IN ('ACTIVE', 'FROZEN', 'CANCELLED', 'EXPIRED')
    )
);
-- 13. CUSTOMER SUBSCRIPTION STATUS/EVENT HISTORY
CREATE TABLE IF NOT EXISTS customer_subscription_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    old_plan_id INTEGER,
    new_plan_id INTEGER,
    event_note TEXT,
    effective_at TIMESTAMP NOT NULL,
    created_by_user_id INTEGER,
    approved_by_user_id INTEGER,
    approval_reference TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enrollment_id) REFERENCES customer_subscriptions(enrollment_id) ON DELETE CASCADE,
    FOREIGN KEY (old_plan_id) REFERENCES subscription_plans(plan_id),
    FOREIGN KEY (new_plan_id) REFERENCES subscription_plans(plan_id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (approved_by_user_id) REFERENCES users(user_id)
);
-- 14. SUBSCRIPTION APPROVAL WORKFLOW
CREATE TABLE IF NOT EXISTS subscription_approvals (
    approval_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_type TEXT NOT NULL,
    request_ref_type TEXT NOT NULL,
    request_ref_id INTEGER NOT NULL,
    requested_by_user_id INTEGER NOT NULL,
    approver_user_id INTEGER,
    approval_status TEXT NOT NULL DEFAULT 'PENDING',
    reason TEXT NOT NULL,
    approved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (requested_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (approver_user_id) REFERENCES users(user_id),
    CHECK (
        approval_status IN ('PENDING', 'APPROVED', 'REJECTED')
    )
);
-- 15. SUBSCRIPTION DISCOUNT OVERRIDES
CREATE TABLE IF NOT EXISTS subscription_discount_overrides (
    override_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INTEGER,
    bill_item_id INTEGER,
    customer_id INTEGER,
    enrollment_id INTEGER,
    requested_discount_percent DOUBLE PRECISION NOT NULL,
    approved_discount_percent DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'PENDING',
    reason TEXT NOT NULL,
    requested_by_user_id INTEGER NOT NULL,
    approved_by_user_id INTEGER,
    approval_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
    FOREIGN KEY (bill_item_id) REFERENCES bill_items(item_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (enrollment_id) REFERENCES customer_subscriptions(enrollment_id),
    FOREIGN KEY (requested_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (approved_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (approval_id) REFERENCES subscription_approvals(approval_id),
    CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')
    )
);
-- 16. SUBSCRIPTION PILOT FEEDBACK TRACKER
CREATE TABLE IF NOT EXISTS subscription_pilot_feedback (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL DEFAULT 'GENERAL',
    severity TEXT NOT NULL DEFAULT 'MEDIUM',
    status TEXT NOT NULL DEFAULT 'OPEN',
    title TEXT NOT NULL,
    details TEXT,
    reported_by_user_id INTEGER NOT NULL,
    owner_user_id INTEGER,
    linked_bill_id INTEGER,
    linked_override_id INTEGER,
    resolution_notes TEXT,
    reported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    FOREIGN KEY (reported_by_user_id) REFERENCES users(user_id),
    FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    FOREIGN KEY (linked_bill_id) REFERENCES bills(bill_id),
    FOREIGN KEY (linked_override_id) REFERENCES subscription_discount_overrides(override_id),
    CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);
-- 17. TAMPER-EVIDENT SUBSCRIPTION AUDIT LOG
CREATE TABLE IF NOT EXISTS subscription_audit_log (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    actor_user_id INTEGER,
    approval_id INTEGER,
    reason TEXT,
    before_json TEXT,
    after_json TEXT,
    previous_checksum TEXT,
    checksum TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (actor_user_id) REFERENCES users(user_id),
    FOREIGN KEY (approval_id) REFERENCES subscription_approvals(approval_id)
);
-- 17A. AI DECISION LOG FOR SUBSCRIPTION WORKFLOWS
CREATE TABLE IF NOT EXISTS subscription_ai_decision_log (
    decision_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_type TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_ref TEXT NOT NULL,
    reason_code TEXT NOT NULL,
    reason_message TEXT NOT NULL,
    decision_payload_json TEXT,
    model_component TEXT,
    model_version TEXT,
    prompt_key TEXT,
    prompt_version INTEGER,
    actor_user_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (actor_user_id) REFERENCES users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_subscription_plans_status ON subscription_plans(status);
CREATE INDEX IF NOT EXISTS idx_subscription_plans_code ON subscription_plans(plan_code);
CREATE INDEX IF NOT EXISTS idx_sub_cat_rules_plan ON subscription_plan_category_rules(plan_id, active);
CREATE INDEX IF NOT EXISTS idx_sub_med_rules_plan ON subscription_plan_medicine_rules(plan_id, active);
CREATE INDEX IF NOT EXISTS idx_sub_med_rules_medicine ON subscription_plan_medicine_rules(medicine_id, active);
CREATE INDEX IF NOT EXISTS idx_customer_subscriptions_customer ON customer_subscriptions(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_customer_subscriptions_plan ON customer_subscriptions(plan_id, status);
CREATE INDEX IF NOT EXISTS idx_customer_subscriptions_end_date ON customer_subscriptions(end_date);
CREATE INDEX IF NOT EXISTS idx_customer_sub_events_enrollment ON customer_subscription_events(enrollment_id, effective_at);
CREATE INDEX IF NOT EXISTS idx_subscription_approvals_status ON subscription_approvals(approval_status, created_at);
CREATE INDEX IF NOT EXISTS idx_subscription_overrides_status ON subscription_discount_overrides(status, created_at);
CREATE INDEX IF NOT EXISTS idx_subscription_feedback_status ON subscription_pilot_feedback(status, reported_at);
CREATE INDEX IF NOT EXISTS idx_subscription_feedback_severity ON subscription_pilot_feedback(severity, reported_at);
CREATE INDEX IF NOT EXISTS idx_subscription_audit_created ON subscription_audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_subscription_audit_entity ON subscription_audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_sub_ai_decision_type_created ON subscription_ai_decision_log(decision_type, created_at);
CREATE INDEX IF NOT EXISTS idx_sub_ai_subject_created ON subscription_ai_decision_log(subject_type, subject_ref, created_at);
CREATE INDEX IF NOT EXISTS idx_sub_ai_reason_created ON subscription_ai_decision_log(reason_code, created_at);
-- 18. WEEKLY MATERIALIZED ANALYTICS SUMMARY TABLES
CREATE TABLE IF NOT EXISTS subscription_weekly_summary (
    summary_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_date TEXT NOT NULL,
    week_end_date TEXT NOT NULL,
    timezone_name TEXT NOT NULL,
    total_bill_count INTEGER NOT NULL DEFAULT 0,
    subscription_bill_count INTEGER NOT NULL DEFAULT 0,
    gross_amount_before_discount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    net_billed_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_savings DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    leakage_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    active_subscribers_snapshot INTEGER NOT NULL DEFAULT 0,
    renewals_due_next_7_days INTEGER NOT NULL DEFAULT 0,
    pending_override_count INTEGER NOT NULL DEFAULT 0,
    high_pricing_alert_count INTEGER NOT NULL DEFAULT 0,
    high_override_abuse_signal_count INTEGER NOT NULL DEFAULT 0,
    open_high_critical_feedback_count INTEGER NOT NULL DEFAULT 0,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (week_start_date, timezone_name)
);
CREATE TABLE IF NOT EXISTS subscription_weekly_plan_summary (
    week_start_date TEXT NOT NULL,
    week_end_date TEXT NOT NULL,
    timezone_name TEXT NOT NULL,
    plan_id INTEGER NOT NULL,
    plan_code TEXT,
    plan_name TEXT,
    bill_count INTEGER NOT NULL DEFAULT 0,
    gross_amount_before_discount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    net_billed_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_savings DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    average_savings_per_bill DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    leakage_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (week_start_date, timezone_name, plan_id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(plan_id)
);
CREATE INDEX IF NOT EXISTS idx_subscription_weekly_summary_week ON subscription_weekly_summary(week_start_date, timezone_name);
CREATE INDEX IF NOT EXISTS idx_subscription_weekly_plan_summary_week ON subscription_weekly_plan_summary(week_start_date, timezone_name);
-- Phase 1 Subscription Discount Columns
ALTER TABLE bills
ADD COLUMN subscription_enrollment_id INTEGER;
ALTER TABLE bills
ADD COLUMN subscription_plan_id INTEGER;
ALTER TABLE bills
ADD COLUMN subscription_discount_percent DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE bills
ADD COLUMN subscription_savings_amount DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE bills
ADD COLUMN subscription_approval_reference TEXT;
ALTER TABLE bill_items
ADD COLUMN subscription_discount_percent DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE bill_items
ADD COLUMN subscription_discount_amount DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE bill_items
ADD COLUMN subscription_rule_source TEXT;
ALTER TABLE subscription_plans
ADD COLUMN default_discount_percent DOUBLE PRECISION DEFAULT 0.0;
-- ======================== PHASE 1: POS FEATURES ========================
-- 19. BARCODE COLUMN ON MEDICINES
ALTER TABLE medicines
ADD COLUMN barcode TEXT;
CREATE INDEX IF NOT EXISTS idx_medicines_barcode ON medicines(barcode);
-- 20. PAYMENT SPLITS (for mixed/split payments)
CREATE TABLE IF NOT EXISTS payment_splits (
    split_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INTEGER NOT NULL,
    payment_method TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    reference_number TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
    CHECK (
        payment_method IN (
            'CASH',
            'UPI',
            'CARD',
            'CREDIT',
            'CHEQUE',
            'OTHER'
        )
    )
);
CREATE INDEX IF NOT EXISTS idx_payment_splits_bill ON payment_splits(bill_id);
-- 21. HELD ORDERS (layaway / hold-and-recall)
CREATE TABLE IF NOT EXISTS held_orders (
    hold_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER,
    user_id INTEGER,
    items_json TEXT NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'HELD',
    held_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recalled_at TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    CHECK (status IN ('HELD', 'RECALLED', 'CANCELLED'))
);
CREATE INDEX IF NOT EXISTS idx_held_orders_status ON held_orders(status, held_at DESC);
CREATE INDEX IF NOT EXISTS idx_held_orders_user ON held_orders(user_id, status);
-- 22. RECEIPT SETTINGS (pharmacy branding for receipts)
CREATE TABLE IF NOT EXISTS receipt_settings (
    setting_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_name TEXT NOT NULL DEFAULT 'MediManage Pharmacy',
    address_line1 TEXT,
    address_line2 TEXT,
    phone TEXT,
    email TEXT,
    gst_number TEXT,
    logo_path TEXT,
    footer_text TEXT DEFAULT 'Thank you for your purchase!',
    show_barcode_on_receipt INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- 23. PRICE OVERRIDE ON BILL ITEMS
ALTER TABLE bill_items
ADD COLUMN price_override DOUBLE PRECISION;
ALTER TABLE bill_items
ADD COLUMN override_reason TEXT;
ALTER TABLE bill_items
ADD COLUMN override_by_user_id INTEGER;
-- ======================== PHASE 2: BACKEND MANAGEMENT ========================
-- 24. SUPPLIERS
CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    gst_number TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name);
CREATE INDEX IF NOT EXISTS idx_suppliers_active ON suppliers(active);
-- 25. PURCHASE ORDERS
CREATE TABLE IF NOT EXISTS purchase_orders (
    po_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expected_delivery TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    notes TEXT,
    created_by_user_id INTEGER,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(user_id),
    CHECK (
        status IN (
            'DRAFT',
            'ORDERED',
            'PARTIAL',
            'RECEIVED',
            'CANCELLED'
        )
    )
);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_supplier ON purchase_orders(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_status ON purchase_orders(status);
-- 26. PURCHASE ORDER ITEMS
CREATE TABLE IF NOT EXISTS purchase_order_items (
    poi_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    ordered_qty INTEGER NOT NULL,
    received_qty INTEGER NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id) ON DELETE CASCADE,
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id)
);
CREATE INDEX IF NOT EXISTS idx_poi_po ON purchase_order_items(po_id);
-- 27. EMPLOYEE ATTENDANCE
CREATE TABLE IF NOT EXISTS employee_attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    check_in_time TIMESTAMP NOT NULL,
    check_out_time TIMESTAMP,
    date DATE NOT NULL,
    total_hours DOUBLE PRECISION,
    notes TEXT,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_attendance_user_date ON employee_attendance(user_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON employee_attendance(date);
-- 28. SUPPLIER LINK ON MEDICINES
ALTER TABLE medicines
ADD COLUMN supplier_id INTEGER;
-- ======================== PHASE 3: ADVANCED FEATURES ========================
-- 29. LOCATIONS (multi-pharmacy/warehouse)
CREATE TABLE IF NOT EXISTS locations (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    location_type TEXT NOT NULL DEFAULT 'PHARMACY',
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        location_type IN ('PHARMACY', 'WAREHOUSE', 'CLINIC')
    )
);
-- 30. LOCATION STOCK
CREATE TABLE IF NOT EXISTS location_stock (
    location_stock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    min_stock INTEGER NOT NULL DEFAULT 5,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (location_id) REFERENCES locations(location_id),
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id),
    UNIQUE(location_id, medicine_id)
);
CREATE INDEX IF NOT EXISTS idx_location_stock_loc ON location_stock(location_id);
CREATE INDEX IF NOT EXISTS idx_location_stock_med ON location_stock(medicine_id);
-- 31. STOCK TRANSFERS
CREATE TABLE IF NOT EXISTS stock_transfers (
    transfer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_location_id INTEGER NOT NULL,
    to_location_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    requested_by INTEGER,
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (from_location_id) REFERENCES locations(location_id),
    FOREIGN KEY (to_location_id) REFERENCES locations(location_id),
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id),
    FOREIGN KEY (requested_by) REFERENCES users(user_id),
    CHECK (
        status IN (
            'PENDING',
            'IN_TRANSIT',
            'COMPLETED',
            'CANCELLED'
        )
    )
);
-- 32. LOCATION ON BILLS
ALTER TABLE bills
ADD COLUMN location_id INTEGER;